version: '3.3'
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:v1.0
    ports:
      - 443:443
    volumes:
      - /home/zmakhkha/data/wp:/var/www
    networks:
      - wp_network
    depends_on : 
      - wordpress
    restart: always
    env_file:
      - .env


  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:v1.0
    depends_on:
      - mariadb
    volumes:
      - /home/zmakhkha/data/wp:/var/www
    networks:
      - wp_network
    env_file:
      - .env
    restart: always


  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:v1.0
    volumes:
      - /home/zmakhkha/data/mdb:/var/lib/mysql
    networks:
      - wp_network
    env_file:
      - .env
    restart: always


# # Bonus
  website:
    build: ./requirements/bonus/static/
    image: static:v1.0
    container_name: static
    ports:
      - 2100:2100
    networks:
      - wp_network
    restart: always

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer/
    image: adminer:v1.0
    volumes:
      - /home/zmakhkha/data/mdb:/var/lib/mysql
    ports:
      - 2200:2200
    networks:
      - wp_network
    restart: always

  portainer:
    container_name: portainer
    build: ./requirements/bonus/portainer/
    image: portainer:v1.0
    ports:
      - 2300:9443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - wp_network
    restart: always
  
  ftp:
    # container_name: ftp
    build: ./requirements/bonus/ftp/
    image: ftp:v1.0
    depends_on:
      - wordpress
    volumes:
      - /home/zmakhkha/data/wp:/var/www
    env_file:
      - .env
    ports:
      - "2400:21"
      - "40000-40005:40000-40005"
    networks:
      - wp_network
    restart: always
  
  redis:
    container_name: redis
    build: ./requirements/bonus/redis/
    image: redis:v1.0
    ports:
      - 6379:6379
    volumes:
      - /home/zmakhkha/data/wp:/var/www
    networks:
      - wp_network
    restart: always



networks:
  wp_network:
    driver: bridge